#!/usr/bin/env ruby

require "pleasant_lawyer_cli"

help = <<-HELP
Please provide a pleasant lawyer name or beetil number as input

E.g:
  pl famous money # => 60254
  pl 60254        # => famous money
HELP

if ARGV.length == 1 && %w(-h --help).include?(ARGV[0])
  puts help
  exit 0
end

input = ARGV.join ' '

fail help if input.empty?

output = PleasantLawyer.convert(input)

if output.respond_to? :join
  output = output.join(' ')
end

puts output
