#!/usr/bin/env ruby

require "pleasant_lawyer_cli"


help = <<-HELP
Please provide a pleasant lawyer name or beetil number as input

E.g:
  plco famous money # checks out b_60254
HELP

if ARGV.length == 1 && %w(-h --help).include?(ARGV[0])
  puts help
  exit 0
end

git_input = ARGV.select { |arg| /^-/ =~ arg }.join ' '
pl_input = ARGV.reject { |arg| /^-/ =~ arg }.join ' '

fail help if pl_input.empty?

output = PleasantLawyer.convert(pl_input)

`git checkout #{git_input} b_#{output}`

