#!/usr/bin/env ruby

require 'rubygems'
require "bundler/setup"
require "pleasant_lawyer"

input = ARGV.join ' '

help = <<-HELP
Please provide a pleasant lawyer name or beetil number as input

E.g:
  plco famous money # checks out b_60254
HELP

fail help if input.empty?

output = PleasantLawyer.convert(input)

`git checkout b_#{output}`

