#!/usr/bin/env ruby

require "pleasant_lawyer_cli"

git_input = ARGV.select { |arg| /^-/ =~ arg }.join ' '
pl_input = ARGV.reject { |arg| /^-/ =~ arg }.join ' '

help = <<-HELP
Please provide a pleasant lawyer name or beetil number as input

E.g:
  plco famous money # checks out b_60254
HELP

fail help if pl_input.empty?

output = PleasantLawyer.convert(pl_input)

`git checkout #{git_input} b_#{output}`

